import type { Region } from '@/types/domain';

// Kenya first (the sensible default — all seed/demo data assumes Kenya),
// then roughly by region, matching the design's country sheet.
export const COUNTRIES: { region: Region; name: string; flag: string }[] = [
  { region: 'KE', name: 'Kenya', flag: '🇰🇪' },
  { region: 'UG', name: 'Uganda', flag: '🇺🇬' },
  { region: 'TZ', name: 'Tanzania', flag: '🇹🇿' },
  { region: 'RW', name: 'Rwanda', flag: '🇷🇼' },
  { region: 'ET', name: 'Ethiopia', flag: '🇪🇹' },
  { region: 'SO', name: 'Somalia', flag: '🇸🇴' },
  { region: 'SS', name: 'South Sudan', flag: '🇸🇸' },
  { region: 'BI', name: 'Burundi', flag: '🇧🇮' },
  { region: 'CD', name: 'DR Congo', flag: '🇨🇩' },
  { region: 'ZA', name: 'South Africa', flag: '🇿🇦' },
  { region: 'ZM', name: 'Zambia', flag: '🇿🇲' },
  { region: 'ZW', name: 'Zimbabwe', flag: '🇿🇼' },
  { region: 'BW', name: 'Botswana', flag: '🇧🇼' },
  { region: 'NA', name: 'Namibia', flag: '🇳🇦' },
  { region: 'MZ', name: 'Mozambique', flag: '🇲🇿' },
  { region: 'MW', name: 'Malawi', flag: '🇲🇼' },
  { region: 'AO', name: 'Angola', flag: '🇦🇴' },
  { region: 'MU', name: 'Mauritius', flag: '🇲🇺' },
  { region: 'NG', name: 'Nigeria', flag: '🇳🇬' },
  { region: 'GH', name: 'Ghana', flag: '🇬🇭' },
  { region: 'CI', name: 'Ivory Coast', flag: '🇨🇮' },
  { region: 'SN', name: 'Senegal', flag: '🇸🇳' },
  { region: 'CM', name: 'Cameroon', flag: '🇨🇲' },
  { region: 'EG', name: 'Egypt', flag: '🇪🇬' },
  { region: 'MA', name: 'Morocco', flag: '🇲🇦' },
  { region: 'TN', name: 'Tunisia', flag: '🇹🇳' },
  { region: 'GB', name: 'United Kingdom', flag: '🇬🇧' },
  { region: 'IE', name: 'Ireland', flag: '🇮🇪' },
  { region: 'DE', name: 'Germany', flag: '🇩🇪' },
  { region: 'FR', name: 'France', flag: '🇫🇷' },
  { region: 'ES', name: 'Spain', flag: '🇪🇸' },
  { region: 'IT', name: 'Italy', flag: '🇮🇹' },
  { region: 'NL', name: 'Netherlands', flag: '🇳🇱' },
  { region: 'PT', name: 'Portugal', flag: '🇵🇹' },
  { region: 'PL', name: 'Poland', flag: '🇵🇱' },
  { region: 'SE', name: 'Sweden', flag: '🇸🇪' },
  { region: 'NO', name: 'Norway', flag: '🇳🇴' },
  { region: 'CH', name: 'Switzerland', flag: '🇨🇭' },
  { region: 'TR', name: 'Turkey', flag: '🇹🇷' },
  { region: 'US', name: 'United States', flag: '🇺🇸' },
  { region: 'CA', name: 'Canada', flag: '🇨🇦' },
  { region: 'MX', name: 'Mexico', flag: '🇲🇽' },
  { region: 'BR', name: 'Brazil', flag: '🇧🇷' },
  { region: 'AR', name: 'Argentina', flag: '🇦🇷' },
  { region: 'CL', name: 'Chile', flag: '🇨🇱' },
  { region: 'CO', name: 'Colombia', flag: '🇨🇴' },
  { region: 'AE', name: 'United Arab Emirates', flag: '🇦🇪' },
  { region: 'SA', name: 'Saudi Arabia', flag: '🇸🇦' },
  { region: 'QA', name: 'Qatar', flag: '🇶🇦' },
  { region: 'OM', name: 'Oman', flag: '🇴🇲' },
  { region: 'IL', name: 'Israel', flag: '🇮🇱' },
  { region: 'IN', name: 'India', flag: '🇮🇳' },
  { region: 'PK', name: 'Pakistan', flag: '🇵🇰' },
  { region: 'LK', name: 'Sri Lanka', flag: '🇱🇰' },
  { region: 'BD', name: 'Bangladesh', flag: '🇧🇩' },
  { region: 'CN', name: 'China', flag: '🇨🇳' },
  { region: 'JP', name: 'Japan', flag: '🇯🇵' },
  { region: 'KR', name: 'South Korea', flag: '🇰🇷' },
  { region: 'MY', name: 'Malaysia', flag: '🇲🇾' },
  { region: 'SG', name: 'Singapore', flag: '🇸🇬' },
  { region: 'ID', name: 'Indonesia', flag: '🇮🇩' },
  { region: 'TH', name: 'Thailand', flag: '🇹🇭' },
  { region: 'PH', name: 'Philippines', flag: '🇵🇭' },
  { region: 'VN', name: 'Vietnam', flag: '🇻🇳' },
  { region: 'AU', name: 'Australia', flag: '🇦🇺' },
  { region: 'NZ', name: 'New Zealand', flag: '🇳🇿' },
];
